[{"name": "test.test_positive_list.PositiveList.test_calls", "status": "failed", "message": "Expected 'filter' to have been called.", "passed": false, "points": ["p01-17.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e17_positive_list/test/test_positive_list.py\", line 35, in test_calls\n    f.assert_called()\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/mock.py\", line 876, in assert_called\n    raise AssertionError(msg)\n"]}, {"name": "test.test_positive_list.PositiveList.test_first", "status": "failed", "message": "Lists differ: [] != [2, 1]\n\nSecond list contains 2 additional elements.\nFirst extra element 0:\n2\n\n- []\n+ [2, 1] : Wrong result for list [2, -2, 0, 1, -7]!", "passed": false, "points": ["p01-17.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e17_positive_list/test/test_positive_list.py\", line 22, in test_first\n    self.assertEqual(result, [2,1], msg=\"Wrong result for list %s!\" % L)\n"]}, {"name": "test.test_positive_list.PositiveList.test_random", "status": "failed", "message": "Lists differ: [] != [79, 20, 73, 79, 75, 28, 68, 60, 59, 27, 4[69 chars], 57]\n\nSecond list contains 29 additional elements.\nFirst extra element 0:\n79\n\n- []\n+ [79,\n+  20,\n+  73,\n+  79,\n+  75,\n+  28,\n+  68,\n+  60,\n+  59,\n+  27,\n+  44,\n+  93,\n+  32,\n+  61,\n+  47,\n+  18,\n+  98,\n+  37,\n+  31,\n+  41,\n+  60,\n+  25,\n+  21,\n+  30,\n+  23,\n+  31,\n+  40,\n+  36,\n+  57] : Wrong result for list [ -86   79   20  -65   73   -4  -55   79  -28   75   28  -24  -96  -46\n   68   60   59  -97   27   44  -17   93   32  -25  -41  -28   -1   61\n   47  -23  -90  -11   18   98   37   31   41   -5 -100   60   25   21\n  -12  -46   30   23   31   40   36   57]!", "passed": false, "points": ["p01-17.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e17_positive_list/test/test_positive_list.py\", line 30, in test_random\n    self.assertEqual(result, correct, msg=\"Wrong result for list %s!\" % L)\n"]}]