[{"name": "test.test_sum_equation.SumEquation.test_empty", "status": "failed", "message": "'' != '0 = 0'\n+ 0 = 0 : Incorrect result for an empty input list!", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e19_sum_equation/test/test_sum_equation.py\", line 40, in test_empty\n    self.assertEqual(result, \"0 = 0\", msg=\"Incorrect result for an empty input list!\")\n"]}, {"name": "test.test_sum_equation.SumEquation.test_first", "status": "failed", "message": "'' != '1 + 5 + 7 = 13'\n+ 1 + 5 + 7 = 13 : Incorrect result for input list [1, 5, 7]!", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e19_sum_equation/test/test_sum_equation.py\", line 23, in test_first\n    self.assertEqual(result, \"1 + 5 + 7 = 13\", msg=\"Incorrect result for input list %s!\" % L)\n"]}, {"name": "test.test_sum_equation.SumEquation.test_random", "status": "failed", "message": "None is not true", "passed": false, "points": ["p01-19.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e19_sum_equation/test/test_sum_equation.py\", line 30, in test_random\n    self.assertTrue(m)\n"]}]