[{"name": "test.test_distinct_characters.DistinctCharacters.test_empty", "status": "passed", "message": "", "passed": true, "points": ["p01-12.1"], "backtrace": []}, {"name": "test.test_distinct_characters.DistinctCharacters.test_first", "status": "errored", "message": "'check'", "passed": false, "points": ["p01-12.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e12_distinct_characters/test/test_distinct_characters.py\", line 38, in test_first\n    self.assertEqual(d[\"check\"], 4, msg=\"Number of distinct characters of word 'check' was incorrect!\")\n"]}, {"name": "test.test_distinct_characters.DistinctCharacters.test_random", "status": "failed", "message": "0 != 22", "passed": false, "points": ["p01-12.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e12_distinct_characters/test/test_distinct_characters.py\", line 51, in test_random\n    self.assertEqual(len(d), len(set(L)))\n"]}]