[{"name": "test.test_two_dice_comprehension.TwoDice.test_content", "status": "failed", "message": "Regex didn't match: '\\\\((\\\\d),\\\\s*(\\\\d)\\\\)' not found in '' : Line  did not contain a pair of numbers!", "passed": false, "points": ["p01-15.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e15_two_dice_comprehension/test/test_two_dice_comprehension.py\", line 29, in test_content\n    self.assertRegex(line, pattern, msg=\"Line %s did not contain a pair of numbers!\" % line)\n"]}, {"name": "test.test_two_dice_comprehension.TwoDice.test_lines", "status": "failed", "message": "1 != 4 : Output should contain four lines!", "passed": false, "points": ["p01-15.1"], "backtrace": ["  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n", "  File \"/Users/carlygordon/opt/anaconda3/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n", "  File \"/Users/carlygordon/Desktop/DataAnalysis/mooc-data-analysis-with-python-2022/part01-e15_two_dice_comprehension/test/test_two_dice_comprehension.py\", line 21, in test_lines\n    self.assertEqual(len(result), 4, msg=\"Output should contain four lines!\")\n"]}]